#!/usr/bin/env python

import argparse
import datetime
import time
import os
import os.path

import PyRSS2Gen
import feedparser

args = None

def main():
    global args
    parser = argparse.ArgumentParser()
    parser.add_argument('--feed-file',required=True, help="The file to which the message will be appended")
    parser.add_argument('--feed-title', help="The feed title. It defaults to the FEED_FILE if left blank.")
    parser.add_argument('--feed-description', help="The feed description. It defaults to the FEED_FILE if left blank.")
    parser.add_argument('--max-count', default=100, help="The maximum amount of entries in the feed. If exceeded older entries are erased.")
    parser.add_argument('message', help="The message to write to the feed")
    args = parser.parse_args()
    if args.feed_title is None:
        args.feed_title = os.path.basename(args.feed_file)
    if args.feed_description is None:
        args.feed_description = os.path.basename(args.feed_file)

    if not os.path.exists(args.feed_file):
        create_feed()

    # Read feed
    data = feedparser.parse(args.feed_file)

    # Prune items to max size
    args.max_count = int(args.max_count)
    if len(data.entries) >= args.max_count:
        data.entries = data.entries[-args.max_count+1:]

    # Append new item
    data.entries.append(
        {
            'title': args.message,
            'id': str(int(time.time()*100)),
            'published': datetime.datetime.utcnow(),
        }
    )

    write_feed(data)



def create_feed():
    logdir = os.path.dirname(args.feed_file)
    if logdir != '' and not os.path.exists(logdir):
        os.makedirs(logdir)
    rss = PyRSS2Gen.RSS2(
        title = args.feed_title,
        description = args.feed_description,
        link = 'file:///{}'.format(args.feed_file)
    )
    with open(args.feed_file,'w') as fh:
        rss.write_xml(fh)

def write_feed(data):
    items = []
    for entry in data.entries:
        item = PyRSS2Gen.RSSItem(title = entry['title'])
        if 'id' in entry:
            item.guid = PyRSS2Gen.Guid(entry['id'],False)
        if 'published' in entry:
            item.pubDate = entry['published']
        items.append(item)

    rss = PyRSS2Gen.RSS2(
        title = args.feed_title,
        link = 'file://' + args.feed_file,
        description = args.feed_description,
        items = items
    )
    with open(args.feed_file,'w') as fh:
        rss.write_xml(fh)


if __name__ == '__main__':
    main()
